apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: y8eaqgwzs-python 
  janus-idp.io/tekton: y8eaqgwzs-python
  backstage.io/kubernetes-id: y8eaqgwzs-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: y8eaqgwzs-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml